#!/usr/bin/env perl

# Enable strict interpretation and define metadata
use warnings;
use strict;
my $version = "v0.1.0";

# Splash text
print "splitOS installer image builder " . $version . "\n";

# Check if a kernel image exists
my $kernel;
if (-e "./bzImage") {
    $kernel = "./bzImage";
} elsif (-e "./zImage") {
    $kernel = "./zImage";
} else {
    die "Could not find a local kernel image. Aborted";
}
print "Local kernel image located in current directory! Using.\n";

# Open the kernel image for an integrity check
open my $fh, '<', $kernel or die "Could not open kernel image for integrity check. Aborted";

# Read the magic number of the kernel and close the file handle
my $magicNumber;
seek $fh, 514, 0 or die "Could not seek to magic number. Aborted";
read $fh, $magicNumber, 4 or die "Could not read magic number. Aborted";
close $fh;

# Check if the magic number is correct
if ($magicNumber eq "HdrS") {
    print "Kernel validity check passed!\n";
} else {
    die "Kernel validity check failed. Aborted";
}